language: python

cache: pip

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment
    - bash prepare_tests.sh

install:
    - pip install -U pip wheel
    - pip install -e .[tests,docs]
    - pip install python-coveralls

script:
    - py.test tests
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar

after_success:
    - coveralls
